name: Tests Athena Bank Fintech

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
        
jobs:
  tests:
    runs-on: ubuntu-latest

    services: 
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: 6007
      VITE_API_URL: http://localhost:6007/api

    steps:
      - name: Checkout current repo which includes workflow
        uses: actions/checkout@v3

      - name: Clone Athena Bank Fintech repo
        run: git clone https://github.com/Atenea-Conocimientos/redux-athena-bank.git app

      - name: Create file .env for the backend
        run: |
          echo "MONGO_URI=${{ env.MONGO_URI }}" > app/backend/.env
          echo "JWT_SECRET=${{ env.JWT_SECRET }}" >> app/backend/.env
          echo "PORT=${{ env.PORT }}" >> app/backend/.env
          echo "VITE_API_URL=${{ env.VITE_API_URL }}" >> app/backend/.env

      - name: Install backend dependencies
        run: |
          cd app/backend
          npm install

      - name: Run the backend 
        run: |
          cd app/backend
          npm run dev > backend.log 2>&1 &

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Wait for backend
        run: wait-on tcp:6007

      - name: Install frontend dependencies
        run: |
          cd app/frontend
          npm install
          env: ${{ env.VITE_API_URL }}

      - name: Wait for frontend
        run: wait-on http://localhost:3000
